test_bigquery_profile:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: oauth
      project: personal-381013
      dataset: cue_analytics
      threads: 4
      job_creation_timeout_seconds: 30
      job_execution_timeout_seconds: 86400
      job_retries: 5
      job_retry_deadline_seconds: 1800
      location: EU
